In [1]:
using JuMP, Clp

In [2]:
function objective(u,d)
    return Int(-u + 2*(min(d,u )))
end

objective (generic function with 1 method)

In [3]:
value = [i for i in 6:15]

10-element Array{Int64,1}:
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

Résolution dans le cas où d est connu à l'avance 

In [4]:
m = Model()
@variable(m, u[1:10] , Bin)
d = rand([6,7,8,9,10,11,12,13,14,15])
cost = [objective(i,d) for i in [6,7,8,9,10,11,12,13,14,15]]
@objective(m, Max, dot(cost, u))
@constraint(m, sum(u) <= 1)
solve(m)

:Optimal

Calcul de la valeur moyenne de l'optimum connu à l'avance soit 
$$inf \mathbb{E}\left(min_u -c u +2 (min(0, d-u))\right) $$

In [36]:
valeurs_successives = Array{Int}(1000)
A = zeros(100, 10)

    

100x10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮                        ⋮                      
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0 

In [37]:
for j in 1:100
    d = rand([6,7,8,9,10,11,12,13,14,15])
    for i in 1:10
    A[j, i] =  objective(i+5,d)
    end
end

In [38]:
A

100x10 Array{Float64,2}:
 6.0  7.0  6.0  5.0   4.0   3.0   2.0   1.0   0.0  -1.0
 6.0  7.0  6.0  5.0   4.0   3.0   2.0   1.0   0.0  -1.0
 6.0  5.0  4.0  3.0   2.0   1.0   0.0  -1.0  -2.0  -3.0
 6.0  7.0  8.0  9.0   8.0   7.0   6.0   5.0   4.0   3.0
 6.0  7.0  6.0  5.0   4.0   3.0   2.0   1.0   0.0  -1.0
 6.0  7.0  8.0  9.0  10.0  11.0  12.0  13.0  12.0  11.0
 6.0  7.0  8.0  9.0   8.0   7.0   6.0   5.0   4.0   3.0
 6.0  5.0  4.0  3.0   2.0   1.0   0.0  -1.0  -2.0  -3.0
 6.0  7.0  8.0  7.0   6.0   5.0   4.0   3.0   2.0   1.0
 6.0  7.0  8.0  9.0  10.0  11.0  12.0  11.0  10.0   9.0
 6.0  7.0  8.0  9.0  10.0  11.0  12.0  13.0  12.0  11.0
 6.0  7.0  8.0  9.0  10.0   9.0   8.0   7.0   6.0   5.0
 6.0  7.0  8.0  7.0   6.0   5.0   4.0   3.0   2.0   1.0
 ⋮                          ⋮                          
 6.0  7.0  8.0  7.0   6.0   5.0   4.0   3.0   2.0   1.0
 6.0  7.0  8.0  7.0   6.0   5.0   4.0   3.0   2.0   1.0
 6.0  7.0  8.0  9.0   8.0   7.0   6.0   5.0   4.0   3.0
 6.0  7.0  6.0  5.0   4

In [39]:
m = Model()
@variable(m, u[1:10] , Bin)
@objective(m, Max, sum(A* u))
@constraint(m, sum(u) <= 1)
solve(m)


:Optimal

In [40]:
getvalue(dot(value,u))

10.0

Maintenant interressons nous au meilleur cas en moyenne, c'est à dire à $$\mathbb{E}(inf ) $$ c'est à dire à l'optimum sans connaissance à priori de la demande en journaux.

In [ ]:
m = Model()
@variable(m, u[1:10] , Bin)
for i in 1:1000
    d = rand([6,7,8,9,10,11,12,13,14,15])
    cost = [objective(i,d) for i in [6,7,8,9,10,11,12,13,14,15]]
    @objective(m, Max, dot(cost, u))
    @constraint(m, sum(u) <= 1)
    solve(m)
    valeurs_successives[i] = dot(value, getvalue(u))
end
print(sum(valeurs_successives)/1000)

In [ ]:
sum(valeurs_successives)/100

In [ ]:

for i in 1:10
    println("u[$i] = ", getvalue(u[i]))
end

In [ ]:
d